    public void testUnique() throws Exception {
        HashSet<Integer> result = new HashSet<>(8);
        result.add(Integer.valueOf(90));
        result.add(Integer.valueOf(4));
        result.add(Integer.valueOf(8));
        result.add(Integer.valueOf(43));
        result.add(Integer.valueOf(61));
        result.add(Integer.valueOf(20));
        result.add(Integer.valueOf(29));
        result.add(Integer.valueOf(12));
        performObjectTest("Collection_Unique", result);
    }

