    @Test
    public void testModuloInvalidInitOneArg() {
        try {
            ff.function(functionName, ff.literal(13));
        } catch (RuntimeException e) {
            Assert.assertEquals("Unable to find function " + functionName, e.getMessage());
            return;
        }

        Assert.fail("Exception not thrown");
    }

