    @Test
    public void testDispose() throws IOException {
        store.dispose();
        try {
            ((ArcSDEDataStore) store).getSession(Transaction.AUTO_COMMIT);
            fail("Expected IllegalStateException when the datastore has been disposed");
        } catch (IllegalStateException e) {
            assertTrue(true);
        } finally {
            // dispose test data so next test does not fail due to pool being
            // closed
            testData.tearDown(false, true);
            testData = null;
        }
    }

